http://{{host}}:{{port}}/simulation/start

> {%
    client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status code is not 200, but " + response.status)
    })
%}

###
http://{{host}}:{{port}}/simulation/createBookstores

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status code is not 200, but " + response.status)
    })
%}

###
